[Issue: #24] Feat: Add multithreading utilities
DHBW-Inf/Toolbox pull request #25
Opened 2024-09-29 14:54 UTC by matteokosina

## Description of Changes

This PR introduces multiple ways of implementing multithreading in Java.

## Verify

- [x] If code was changed, unit tests were added
- [x] If code was changed, the changes are documented in JavaDoc comments
- [x] If code was changed, it does not require external dependencies
- [x] The title uses the appropriate prefix (`chore`, `fix`, `feat`, `feat!`) for automatic versioning
- [x] All changes are listed in `release.md`.

## Reference

- #24

2024-09-29 20:16 UTC, habetuz commented
See https://github.com/DHBW-Inf/Toolbox/issues/24#issuecomment-2381588514

2024-09-29 20:17 UTC, habetuz requested changes
See https://github.com/DHBW-Inf/Toolbox/issues/24#issuecomment-2381588514

2024-10-02 06:48 UTC, tsg100 approved these changes
Looks good to me :)

2024-10-02 06:49 UTC, tsg100 approved these changes
Looks good to me :)

2025-01-27 20:19 UTC, closed without merging