feat: Add random utilities
DHBW-Inf/Toolbox pull request #33
Opened 2024-10-02 06:32 UTC by tsg100

Added some basic RandomUtils, including generating Random Numbers, Floats, Doubles and Integers. Also, a random picker for Lists and a random color generator is included.

## Description of Changes

-- describe what you changed / added ---

## Verify

- [X] If code was changed, unit tests were added
- [X] If code was changed, the changes are documented in JavaDoc comments
- [X] If code was changed, it does not require external dependencies
- [X] The title uses the appropriate prefix (`chore`, `fix`, `feat`, `feat!`) for automatic versioning
- [X] All changes are listed in `release.md`.

## Reference

Add random utilities #26

2024-10-02 07:08 UTC, habetuz requested changes

2024-10-02 07:08 UTC, habetuz commented on src/main/java/de/tinf/collections/RandomUtils.java
> +     * @param maxValue Upper bound of desired Number
```suggestion
     * @param minValue Lower bound (including) of desired Number
     * @param maxValue Upper bound (including) of desired Number
```

2024-10-02 07:08 UTC, habetuz commented on src/main/java/de/tinf/collections/RandomUtils.java
> +    }
Change this to generics so that you do not have to cast the result.

We also used arrays everywhere else, we might to the same here.

2024-10-02 07:08 UTC, habetuz commented on src/main/java/de/tinf/collections/RandomUtils.java
> +    }
Add parameters to specify a lower and upper bound for the color values like needed in the test exam.

2024-10-02 07:24 UTC, tsg100 commented
@habetuz Willst du überlagerte Funktionen?
Also anstatt getRandomIntFromZero und get RandomInt halt einfach getRandomInt aber je nach dem, wie viele Argumente du angibst halt von 0 bis max oder min bis max?

2024-10-02 07:32 UTC, habetuz commented
> @habetuz Willst du überlagerte Funktionen? Also anstatt getRandomIntFromZero und get RandomInt halt einfach getRandomInt aber je nach dem, wie viele Argumente du angibst halt von 0 bis max oder min bis max?

Ja, fände ich besser. Macht es cleaner zu nutzen.

2024-10-07 10:54 UTC, habetuz approved these changes

2024-10-07 10:54 UTC, merged